Repository BoostIO/Boostnote, pull requests merged in 2018-12, with the labels that each got.

#2383 export folder should also export the attachments -> fixes #2374
  browser/components/MarkdownPreview.js
  browser/main/SideNav/StorageItem.js
  browser/main/lib/dataApi/exportFolder.js
  browser/main/lib/dataApi/exportNote.js
  package.json
  yarn.lock
Labels: approved :+1:

#2637 Warning when printing snippet
  browser/main/Detail/InfoPanel.js
  browser/main/Detail/InfoPanelTrashed.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/NoteList/index.js
  lib/main-menu.js
Labels: next release (v0.11.12)

#2666 Menu items overhaul
  browser/main/NoteList/index.js
  lib/main-menu.js
Labels: next release (v0.11.12)

#2672 Handle encoded uri path on `copyFile`
  browser/main/lib/dataApi/copyFile.js
  tests/dataApi/copyFile-test.js
Labels: next release (v0.11.12)

#2685 Fixed Build Badge Alignment w/ Fixed link
  readme.md
Labels: approved :+1:

#2684 Dragged note highlighting
  browser/main/SideNav/StorageItem.js
Labels: approved :+1:

#2730 Fixed windows debug path
  .vscode/launch.json
Labels: next release (v0.11.13)

#2739 Https link to EditorConfig.org
  .editorconfig
Labels: next release (v0.11.13)

#2741 fixed issue #2729
  browser/components/markdown.styl
Labels: approved :+1:

#2704 Update tabs ui
  browser/components/SnippetTab.styl
  browser/main/Detail/SnippetNoteDetail.styl
  browser/styles/index.styl
Labels: approved :+1:

#2743 fix min width of note list
  browser/main/Main.js
Labels: next release (v0.11.13)

#2682 Feature - Line highlighting within code block #2469
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/newNote.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Main.js
  browser/main/NoteList/index.js
  browser/main/lib/dataApi/createNote.js
  browser/main/lib/dataApi/createSnippet.js
  browser/main/lib/dataApi/migrateFromV5Storage.js
  browser/main/lib/dataApi/updateNote.js
  browser/main/lib/dataApi/updateSnippet.js
  tests/dataApi/createNote-test.js
  tests/dataApi/createSnippet-test.js
  tests/dataApi/updateNote-test.js
Labels: next release (v0.11.13)

#2692 Fix issue 2557 katex alignment in display math
  browser/components/markdown.styl
Labels: next release (v0.11.13)

#2746 Fix Cmd+Left to go to end of line on Mac
  browser/components/CodeEditor.js
Labels: next release (v0.11.13)

#2456 lint before commit
  package.json
  yarn.lock
Labels: next release (v0.11.13)

#2465 add image gallery
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/lib/markdown.js
  browser/main/lib/dataApi/attachmentManagement.js
  package.json
  yarn.lock
Labels: approved :+1:

#2591 drag image into preview
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.13)

#2455 fix scrolling in note list
  browser/main/NoteList/index.js
  browser/main/TopBar/index.js
Labels: next release (v0.11.13)

#2747 fix paste image
  browser/components/CodeEditor.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: next release (v0.11.13)

#2756 Fix feature 'saveTagsAlphabetically'
  browser/main/Detail/TagSelect.js
Labels: next release (v0.11.13)

#2755 Create FAQ.md
  FAQ.md
Labels: next release (v0.11.13)
