Repository BoostIO/Boostnote, pull requests merged in 2018-06, with the labels that each got.

#1848 Text expansion support
  browser/components/CodeEditor.js
  browser/components/MarkdownPreview.js
  browser/lib/consts.js
  browser/main/SideNav/index.js
  browser/main/lib/dataApi/createSnippet.js
  browser/main/lib/dataApi/deleteSnippet.js
  browser/main/lib/dataApi/fetchSnippet.js
  browser/main/lib/dataApi/index.js
  browser/main/lib/dataApi/updateSnippet.js
  browser/main/modals/PreferencesModal/SnippetEditor.js
  browser/main/modals/PreferencesModal/SnippetList.js
  browser/main/modals/PreferencesModal/SnippetTab.js
  browser/main/modals/PreferencesModal/SnippetTab.styl
  browser/main/modals/PreferencesModal/index.js
  package.json
  tests/dataApi/createSnippet-test.js
  tests/dataApi/deleteSnippet-test.js
  tests/dataApi/updateSnippet-test.js
  yarn.lock
Labels: in progress

#1949 Fix legacy attachment issues
  browser/components/MarkdownPreview.js
  browser/main/lib/dataApi/attachmentManagement.js
Labels: in review

#1996 Added custom markdown css
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: in review

#1955 Update to the latest Electron version (1.8.7)
  package.json
  yarn.lock
Labels: in review

#2024 Fix yarn.lock file
  yarn.lock
Labels: in review

#1963 OnBlur throws exceptions if the notetype is snippet -> Fixes #1962
  browser/main/lib/dataApi/attachmentManagement.js
  tests/dataApi/attachmentManagement.test.js
Labels: next release (v0.11.6)

#1993 Include markdown-it-smartArrow. Toggle it via settings and disable it…
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es-ES.json
  locales/fa.json
  locales/fr.json
  locales/hu.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru.json
  locales/sq.json
  locales/zh-CN.json
  locales/zh-TW.json
  package.json
  yarn.lock
Labels: in progress

#2041 Fix typo of MarkdownEditor.js
  browser/components/MarkdownEditor.js
Labels: next release (v0.11.6)

#1928 update locales/zh-CN
  locales/zh-CN.json
Labels: next release (v0.11.6)

#1989 Create a image tag when pasting image url
  browser/components/CodeEditor.js
Labels: next release (v0.11.6)

#2019 open local file by shell
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.6)

#2017 Added Turkish translation
  browser/lib/Languages.js
  locales/tr.json
Labels: next release (v0.11.6)

#1969 added zoom in & zoom out window feature
  lib/main-menu.js
Labels: discussion, in review

#2047 Fix wrong path of snippets.json
  browser/lib/consts.js
Labels: next release (v0.11.6)

#2057 Add missing Japanese translations
  locales/ja.json
Labels: in review

#2058 Fix en.json
  locales/en.json
Labels: in review

#2060 [Dark Theme]: Fixes the text color for an active note with an empty title
  browser/components/NoteItemSimple.styl
Labels: in review

#2056 Fixed Keyboard tag unvisible in monokai theme[#1945]
  browser/components/markdown.styl
Labels: in review

#2062 Add new future resize editor & Preview Panes by dragging.(#1977)
  browser/components/CodeEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/components/MarkdownSplitEditor.styl
  browser/lib/markdown2.js
Labels: in review

#2065 Fix file list blinking on search
  browser/main/NoteList/index.js
  package.json
  yarn.lock
Labels: in review

#2075 Fixed info panel positioning
  browser/main/Detail/InfoPanel.styl
Labels: next release (v0.11.7)

#2054 Upgrade Electron to v2.0.2
  lib/main-window.js
  lib/main.html
  package.json
  yarn.lock
Labels: next release (v0.11.7)

#2127 Update issue template
  ISSUE_TEMPLATE.md
Labels: next release (v0.11.7)

#2107 One more try to fix the handling of images in the legacy location
  browser/main/lib/dataApi/attachmentManagement.js
  tests/dataApi/attachmentManagement.test.js
Labels: next release (v0.11.7)

#2124 [Refactoring] - Removed unused packages
  package.json
  webpack-skeleton.js
  yarn.lock
Labels: next release (v0.11.7)

#2131 Update Electron to v2.0.3
  package.json
  yarn.lock
Labels: next release (v0.11.7)

#2066 Improve Traditional Chinese translation
  locales/zh-TW.json
Labels: next release (v0.11.7)

#2106 fix tiny comment typo
  lib/main-app.js
Labels: next release (v0.11.7)

#2105 update fr translation
  locales/fr.json
Labels: next release (v0.11.7)

#2122 plantuml non-english character support and timing diagram support
  package.json
  yarn.lock
Labels: next release (v0.11.7)

#2125 Fix rendering of admonitions in Windows
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  package.json
  yarn.lock
Labels: help wanted, in review

#2146 update codemirror
  package.json
  yarn.lock
Labels: next release (v0.11.8)

#2144 Add collapsed state for storage
  browser/main/SideNav/StorageItem.js
  browser/main/lib/dataApi/addStorage.js
  browser/main/lib/dataApi/index.js
  browser/main/lib/dataApi/resolveStorageData.js
  browser/main/lib/dataApi/toggleStorage.js
  browser/main/store.js
  tests/dataApi/toggleStorage-test.js
Labels: next release (v0.11.8)

#2138 Improve uitab editor
  browser/components/CodeEditor.js
  browser/lib/consts.js
  browser/lib/normalizeEditorFontFamily.js
  browser/main/modals/PreferencesModal/UiTab.js
  tests/lib/normalize-editor-font-family-test.js
Labels: next release (v0.11.8)

#2135 Improve snippets ui
  browser/main/modals/PreferencesModal/SnippetList.js
  browser/main/modals/PreferencesModal/SnippetTab.js
  browser/main/modals/PreferencesModal/SnippetTab.styl
Labels: next release (v0.11.8)
