Repository BoostIO/Boostnote, pull requests merged in 2018-08, with the labels that each got.

#2230 Fix escape codeblock
  browser/components/MarkdownPreview.js
  browser/lib/markdown-it-sanitize-html.js
  browser/lib/utils.js
  package-lock.json
  tests/lib/escapeHtmlCharacters-test.js
Labels: next release (v0.11.9)

#2171 Fix search value for html export path
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.9)

#2235 add Ditaa support
  browser/lib/markdown.js
Labels: next release (v0.11.9)

#2208 New Feature: Shortcuts for focusing tag editor(CmdOrControl+Shift+T)(#2132)
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/TagSelect.js
  lib/main-menu.js
Labels: next release (v0.11.9)

#2226 Add code snippets to search scope
  browser/lib/search.js
Labels: next release (v0.11.9)

#2231 Mermaid dark theme rendering fix
  browser/components/MarkdownPreview.js
  browser/components/render/MermaidRender.js
Labels: next release (v0.11.9)

#2253 Fix for issue #2088 : snippet notes are not displaying in markdown
  browser/main/lib/dataApi/attachmentManagement.js
Labels: next release (v0.11.9)

#2257 might fixes #1786 --> export attachments for markdown notes
  browser/components/MarkdownPreview.js
  tests/dataApi/attachmentManagement.test.js
Labels: in review :sparkles:

#2074 Blinking markdown crunch fix
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/NoteItem.js
  browser/components/StorageItem.js
  browser/main/Main.js
  lib/main.html
Labels: in progress :construction:

#2283 Fixed snippet list bug
  browser/main/modals/PreferencesModal/SnippetList.js
Labels: next release (v0.11.9)

#2302 restore window position
  lib/main-window.js
Labels: next release (v0.11.9)

#2307 update todo percentage correctly #2267
  browser/lib/getTodoStatus.js
  tests/lib/get-todo-status-test.js
Labels: next release (v0.11.9)

#2284 Add per-folder sort
  .boostnoterc.sample
  browser/main/NoteList/index.js
  browser/main/lib/ConfigManager.js
  tests/lib/rc-parser-test.js
Labels: next release (v0.11.9)

#2303 update electron version
  package.json
  yarn.lock
Labels: next release (v0.11.9)
