Repository BoostIO/Boostnote, pull requests merged in 2018-03, with the labels that each got.

#1575 allow publishing markdown to wordpress
  browser/components/NoteItem.js
  browser/main/NoteList/index.js
  browser/main/lib/ConfigManager.js
  browser/main/lib/dataApi/updateNote.js
  browser/main/modals/PreferencesModal/Blog.js
  browser/main/modals/PreferencesModal/index.js
Labels: in review

#1579 Move images between storages together with note
  browser/main/SideNav/StorageItem.js
  browser/main/lib/dataApi/copyImage.js
  browser/main/lib/dataApi/exportNote.js
  browser/main/lib/dataApi/moveNote.js
Labels: next release (v0.11.0)

#1583 Adds the ability to copy the note link from the note list
  browser/main/NoteList/index.js
Labels: next release (v0.11.0)

#1584 Fixes UI overlapping in the snippet editor (bottom options)
  browser/styles/index.styl
Labels: next release (v0.11.0)

#1591 Fixed bad merge; closes #1586; related to #1521
  browser/components/CodeEditor.js
Labels: next release (v0.11.0)

#1593 Add search tweaks; closes 1525 closes 1167
  browser/components/CodeEditor.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/NoteList/index.js
  browser/main/TopBar/TopBar.styl
  browser/main/TopBar/index.js
  lib/main-menu.js
Labels: in review

#1594 Fix insertion in Markdown lists - #1588 & 1605
  extra_scripts/boost/boostNewLineIndentContinueMarkdownList.js
  lib/main.html
  node_modules/boost/boostNewLineIndentContinueMarkdownList.js
Labels: next release (v0.11.0)

#1601 fixed missing zoom button - #1598
  browser/main/StatusBar/StatusBar.styl
Labels: next release (v0.11.0)

#1611 add Toggle FullScreen feat + shortcut
  lib/main-menu.js
Labels: next release (v0.11.0)

#1612 Properly decoding for the title of pasted website
  browser/components/CodeEditor.js
  package.json
  yarn.lock
Labels: in review

#1634 SECURITY HOTFIX - Remove XSS attack
  browser/lib/markdown-it-sanitize-html.js
  browser/lib/markdown.js
  package.json
Labels: next release (v0.11.0)

#1639 add UTF-8 tag to HTML export (fixes #1624)
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.0)

#1643 Export responsive html, fixes #1442
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.0)

#1648 fixed code block style in exported HTML file
  browser/components/MarkdownPreview.js
  browser/lib/markdown.js
Labels: next release (v0.11.0)

#1616 Sort tags alphabetically
  browser/main/SideNav/index.js
Labels: next release (v0.11.0)

#1617 Folders in the side nav are now draggable
  browser/components/StorageItem.js
  browser/main/SideNav/StorageItem.js
  browser/main/SideNav/index.js
Labels: in review, next release (v0.11.0)

#1621 Added support for toggling smart quotes in preview
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  docs/zh_TW/build.md
Labels: in review, next release (v0.11.0)

#1650 Update KaTeX Library from 0.8.3 to 0.9.0.
  package.json
  yarn.lock
Labels: next release (v0.11.0)

#1636 remove volatile hash from note links - #1623
  browser/components/MarkdownPreview.js
  browser/components/NoteItem.js
  browser/components/NoteItemSimple.js
  browser/lib/keygen.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/index.js
  browser/main/NoteList/index.js
  browser/main/SideNav/index.js
  browser/main/lib/dataApi/createNote.js
  browser/main/lib/dataApi/moveNote.js
  browser/main/modals/NewNoteModal.js
  browser/main/store.js
  package.json
  tests/fixtures/TestDummy.js
  yarn.lock
Labels: next release (v0.11.0)

#1663 Fix note list UI
  browser/components/NoteItem.js
  browser/components/NoteItem.styl
Labels: in review

#1677 Allow b tag and style attribute
  browser/lib/markdown.js
Labels: next release (v0.11.3)

#1676 hotfix: update markdown render in blog post feature
  browser/main/NoteList/index.js
Labels: next release (v0.11.3)

#1691 Fixed smart quotes when posting a note to blog
  browser/lib/markdown.js
  browser/main/NoteList/index.js
Labels: next release (v0.11.3)

#1640 Localization
  browser/components/SideNavFilter.js
  browser/lib/i18n.js
  browser/main/Detail/InfoPanel.js
  browser/main/Detail/InfoPanelTrashed.js
  browser/main/Detail/PermanentDeleteButton.js
  browser/main/Detail/RestoreButton.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/ToggleModeButton.js
  browser/main/Detail/TrashButton.js
  browser/main/Detail/index.js
  browser/main/Main.js
  browser/main/NewNoteButton/index.js
  browser/main/NoteList/index.js
  browser/main/SideNav/ListButton.js
  browser/main/SideNav/PreferenceButton.js
  browser/main/SideNav/StorageItem.js
  browser/main/SideNav/TagButton.js
  browser/main/StatusBar/index.js
  browser/main/TopBar/index.js
  browser/main/index.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/NewNoteModal.js
  browser/main/modals/PreferencesModal/Blog.js
  browser/main/modals/PreferencesModal/Crowdfunding.js
  browser/main/modals/PreferencesModal/FolderItem.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  browser/main/modals/PreferencesModal/InfoTab.js
  browser/main/modals/PreferencesModal/StorageItem.js
  browser/main/modals/PreferencesModal/StoragesTab.js
  browser/main/modals/PreferencesModal/UiTab.js
  browser/main/modals/PreferencesModal/index.js
  browser/main/modals/RenameFolderModal.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sq.json
  locales/zh-CN.json
  locales/zh-TW.json
  package-lock.json
  package.json
  yarn.lock
Labels: in review

#1678 Added unit tests for lib/markdown
  browser/lib/markdown.js
  lib/main.html
  package.json
  tests/fixtures/markdowns.js
  tests/helpers/setup-browser-env.js
  tests/helpers/setup-electron-mock.js
  tests/lib/markdown-test.js
  tests/lib/rc-parser-test.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
  yarn.lock
Labels: in review

#1566 New snippet tabbar
  browser/components/SnippetTab.styl
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.styl
Labels: in review

#1696 Fix Copy Note Link in Context Menu
  browser/main/NoteList/index.js
Labels: next release (v0.11.3)

#1698 Fix filenames with forbidden symbols during export #1613
  browser/main/lib/dataApi/exportFolder.js
  browser/main/lib/dataApi/exportNote.js
  package.json
  yarn.lock
Labels: next release (v0.11.3)

#1684 Prevent generating a link tag when pasting URL to inside of a link tag.
  browser/components/CodeEditor.js
Labels: in review

#1703 typo
  docs/fr/build.md
Labels: next release (v0.11.3)

#1720 i18n: Add Hungarian (HU) translations
  browser/lib/i18n.js
  browser/main/Main.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  locales/hu.json
Labels: next release (v0.11.3)

#1721 Always quit app when all window closed
  lib/main-app.js
  lib/main-window.js
Labels: next release (v0.11.3)

#1718 Wrap long LaTeX formula in Preview
  browser/components/markdown.styl
Labels: next release (v0.11.3)

#1715 Make sanitization configurable
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt.json
  locales/sq.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: next release (v0.11.3)

#1709 Added editor rulers
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  lib/main.html
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sq.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: next release (v0.11.3)

#1725 Updated German translation
  browser/components/NoteItem.js
  browser/components/NoteItemSimple.js
  browser/components/SnippetTab.js
  browser/main/NoteList/index.js
  browser/main/modals/CreateFolderModal.js
  browser/main/modals/PreferencesModal/FolderItem.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  browser/main/modals/PreferencesModal/StorageItem.js
  browser/main/modals/RenameFolderModal.js
  locales/de.json
Labels: in review, next release (v0.12.0)

#1736 Fixed typo in locales
  locales/da.json
  locales/en.json
  locales/es.json
  locales/ja.json
  locales/no.json
  locales/pl.json
  locales/pt.json
  locales/sq.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: next release (v0.12.0)

#1747 Brazilian Portuguese localization
  locales/pt-BR.json
  locales/pt-PT.json
Labels: next release (v0.12.0)

#1748 Add Spanish (es-ES) locale
  browser/lib/i18n.js
  browser/main/Main.js
  browser/main/lib/ConfigManager.js
  locales/es-ES.json
  locales/es.json
Labels: next release (v0.12.0)

#1741 fix incorrect app closing for linux mint cinnamon
  lib/main-window.js
Labels: next release (v0.12.0)

#1753 Escape html characters before convert to HTML
  browser/components/MarkdownPreview.js
  browser/lib/utils.js
Labels: in review

#1751 Add folding to CodeEditor
  browser/components/CodeEditor.js
  browser/main/global.styl
  lib/main.html
Labels: in review
