Repository BoostIO/Boostnote, pull requests merged in 2018-04, with the labels that each got.

#1774 Translate into Chinese
  locales/zh-CN.json
  locales/zh-TW.json
Labels: next release (v0.12.0)

#1764 Fixed change language in production mode
  browser/lib/i18n.js
  browser/main/lib/ConfigManager.js
Labels: in review

#1752 Add jest and simple test
  .babelrc
  __mocks__/electron.js
  package.json
  tests/components/TagListItem.snapshot.test.js
  tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
  tests/jest.js
  yarn.lock
Labels: in progress

#1742 Add selector to sort tags by counter or alphabetically
  .boostnoterc.sample
  browser/main/SideNav/SideNav.styl
  browser/main/SideNav/index.js
  browser/main/lib/ConfigManager.js
  locales/en.json
  locales/hu.json
  tests/lib/boostnoterc/.boostnoterc.all
Labels: in review

#1724 Fixes #1723
  browser/components/CodeEditor.js
  browser/components/MarkdownPreview.js
Labels: in review

#1701 Fix tag filtering in search entry
  browser/lib/search.js
  tests/lib/search-test.js
Labels: in review

#1809 fixed menu popup on alt key pressed
  browser/main/index.js
Labels: next release (v0.11.5)

#1802 Fixed change some languages
  browser/lib/i18n.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: in review

#1749 Show confirmation dialog when deleting notes from the context menu
  browser/lib/confirmDeleteNote.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/index.js
  browser/main/NoteList/index.js
Labels: next release (v0.11.5)

#1842 Italian translation
  locales/it.json
Labels: next release (v0.11.5)

#1754 Fullscreen shortcut for non macOS
  browser/main/NoteList/index.js
  lib/main-menu.js
Labels: in review

#1858 Fix #1797: In preview window, open external link in external browser.
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.5)

#1834 Edit the localization file of zh-TW
  locales/zh-TW.json
Labels: in review

#1805 Fixed moving notes with images
  browser/main/lib/dataApi/moveNote.js
Labels: in review

#1872 Empty trash menu working in sidebar folded
  browser/components/SideNavFilter.js
Labels: next release (v0.11.5)

#1852 Fixes #1825 Refactoring of the attachment/image management
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/lib/dataApi/attachmentManagement.js
  browser/main/lib/dataApi/copyImage.js
  browser/main/lib/dataApi/exportNote.js
  browser/main/lib/dataApi/moveNote.js
  package.json
  tests/dataApi/attachmentManagement.test.js
  yarn.lock
Labels: in review

#1863 Optimize PNG images losslessly via Google's zopflipng
  resources/app.png
  resources/boostnote-install.png
  resources/boostnote-install@2x.png
  resources/dmg.png
  resources/finder.png
  resources/repository/top.png
  resources/tray-icon-dark.png
  resources/tray-icon-dark@2x.png
  resources/tray-icon-default.png
  resources/tray-icon-default@2x.png
  resources/tray-icon.png
  resources/tray-icon@2x.png
Labels: next release (v0.11.5)

#1875 Monokai theme
  browser/components/NoteItem.styl
  browser/components/NoteItemSimple.styl
  browser/components/RealtimeNotification.styl
  browser/components/SideNavFilter.styl
  browser/components/StorageItem.styl
  browser/components/TodoListPercentage.styl
  browser/components/markdown.styl
  browser/main/Detail/Detail.styl
  browser/main/Detail/FolderSelect.styl
  browser/main/Detail/InfoPanel.styl
  browser/main/Detail/MarkdownNoteDetail.styl
  browser/main/Detail/NoteDetailInfo.styl
  browser/main/Detail/SnippetNoteDetail.styl
  browser/main/Detail/TagSelect.styl
  browser/main/Detail/ToggleModeButton.styl
  browser/main/Main.js
  browser/main/NewNoteButton/NewNoteButton.styl
  browser/main/NoteList/NoteList.styl
  browser/main/SideNav/SideNav.styl
  browser/main/StatusBar/StatusBar.styl
  browser/main/TopBar/TopBar.styl
  browser/main/global.styl
  browser/main/lib/ConfigManager.js
  browser/main/modals/CreateFolderModal.styl
  browser/main/modals/NewNoteModal.styl
  browser/main/modals/PreferencesModal/ConfigTab.styl
  browser/main/modals/PreferencesModal/Crowdfunding.styl
  browser/main/modals/PreferencesModal/FolderItem.styl
  browser/main/modals/PreferencesModal/InfoTab.styl
  browser/main/modals/PreferencesModal/PreferencesModal.styl
  browser/main/modals/PreferencesModal/StoragesTab.styl
  browser/main/modals/PreferencesModal/UiTab.js
  browser/styles/index.styl
Labels: in review
