Repository BoostIO/Boostnote, pull requests merged in 2018-07, with the labels that each got.

#2033 fixed disappearing scroll bar
  browser/components/MarkdownPreview.js
  browser/main/global.styl
Labels: in review

#2197 Improve bracket autoclosing
  browser/components/CodeEditor.js
  browser/main/modals/PreferencesModal/SnippetEditor.js
Labels: next release (v0.11.8)

#2192 Replace shortcut for 'Next Note' and 'Previous Note'
  lib/main-menu.js
Labels: next release (v0.11.8)

#2187 Issue 2156
  browser/main/Detail/index.js
Labels: next release (v0.11.8)

#2183 Flickering on create note
  browser/main/modals/NewNoteModal.js
Labels: next release (v0.11.8)

#2173 Add mermaid support
  browser/components/MarkdownPreview.js
  browser/components/render/MermaidRender.js
  browser/lib/markdown.js
  package.json
  yarn.lock
Labels: next release (v0.11.8)

#2172 Add chartjs support
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/lib/markdown.js
  package.json
  yarn.lock
Labels: in review

#1935 Allow customizing html escape when export note
  browser/components/MarkdownPreview.js
  browser/lib/markdown.js
  browser/lib/utils.js
  tests/lib/escapeHtmlCharacters-test.js
Labels: next release (v0.11.8)

#2168 Fixed 'Focus Search' shortcut
  browser/main/TopBar/index.js
Labels: next release (v0.11.8)

#2145 Markdown Table Formatter
  browser/components/CodeEditor.js
  browser/lib/TextEditorInterface.js
  lib/main-menu.js
  package.json
Labels: next release (v0.11.8)

#2178 Hotkey for toggle editor fullscreen
  browser/main/Detail/FullscreenButton.js
  lib/main-menu.js
Labels: in review

#2205 Fix attachment interoperability between win and *nix
  browser/components/MarkdownPreview.js
  browser/main/lib/dataApi/attachmentManagement.js
  tests/dataApi/attachmentManagement.test.js
Labels: next release (v0.11.8)

#2239 add and improve translation, fix typo
  docs/jp/build.md
Labels: next release (v0.11.9)

#2209 Trash infoPanel Fix
  browser/main/Detail/InfoPanel.styl
Labels: next release (v0.11.9)
