Repository BoostIO/Boostnote, pull requests merged in 2018-02, with the labels that each got.

#1306 Export note with local images
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/lib/dataApi/copyFile.js
  browser/main/lib/dataApi/exportNote.js
Labels: in review

#1531 Remove direct css styling todo lists from MarkdownPreview component
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/lib/markdown.js
  browser/lib/utils.js
Labels: next release (v0.9.0)

#1502 I fixed the behavior of the editor when the enter key is pushed.
  browser/components/CodeEditor.js
  lib/main.html
  node_modules/boost/boostNewLineIndentContinueMarkdownList.js
Labels: bug, next release (v0.9.0)

#1542 Change the company name
  LICENSE
  browser/main/modals/PreferencesModal/InfoTab.js
  contributing.md
Labels: in review

#1539 Added title attributes to elements to show information on hover --- more like a native app feel to it
  browser/main/NoteList/index.js
Labels: in review

#1527 Trashed notes should not be counted
  browser/main/SideNav/index.js
Labels: in review

#1528 UX: Keep selection synced with note visibility
  browser/main/NoteList/index.js
  browser/main/modals/NewNoteModal.js
Labels: in review

#1543 Switch from preview to edit by double click
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: in review

#1509 Feat/display url title
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/finder/NoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: next release (v0.9.1)

#1521 Sync Split Editor scroll position
  browser/components/CodeEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
Labels: in progress

#1570 Fix memory lickage
  browser/main/Detail/MarkdownNoteDetail.js
Labels: bug, next release (v0.9.1)

#1524 Highlight global search matches on code editor
  browser/components/CodeEditor.js
  browser/main/TopBar/index.js
Labels: next release (v0.9.1)

#1533 Display filename in codeblock (resend)
  browser/components/markdown.styl
  browser/lib/markdown.js
Labels: next release (v0.9.1)

#1549 Restore note UX enhancements
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/RestoreButton.js
  browser/main/Detail/RestoreButton.styl
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/NoteList/index.js
Labels: in review

#1558 Added option Empty Trash
  browser/components/SideNavFilter.js
  browser/main/SideNav/index.js
Labels: next release (v0.9.1)

#1567 Fixed ToggleMode button overlapping CSS issue
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/MarkdownNoteDetail.styl
  browser/main/Detail/ToggleModeButton.styl
Labels: in review

#1556 Add storage labels to 'All Notes' and figure a better solution to the dull storage notes list view
  browser/components/NoteItem.js
  browser/components/NoteItem.styl
  browser/components/NoteItemSimple.js
  browser/components/NoteItemSimple.styl
  browser/main/NoteList/index.js
Labels: discussion, next release (v0.9.1)
