Repository BoostIO/Boostnote, pull requests merged in 2018-11, with the labels that each got.

#2278 Add support for converting to MD when paste HTML
  browser/components/CodeEditor.js
  package.json
  yarn.lock
Labels: next release (v0.11.12)

#2547 fix: Fixed storageList typo (storgaeList).
  browser/components/StorageList.js
Labels: approved :+1:

#2511 Fixed "Save as HTML" to respect blockquotes.
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.12)

#2484 fix segmentation fault with glibc 2.28
  dev-scripts/dev.js
  lib/main-window.js
  package.json
Labels: next release (v0.11.12)

#2342 fixing inline html
  browser/lib/markdown-it-sanitize-html.js
  browser/lib/markdown.js
  tests/fixtures/markdowns.js
  tests/lib/markdown-test.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
Labels: approved :+1:

#2430 Fix errors when saving a blank hotkey
  browser/main/modals/PreferencesModal/HotkeyTab.js
Labels: next release (v0.11.12)

#2434 Remove console.logs
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Main.js
  browser/main/NoteList/index.js
  browser/main/SideNav/index.js
  browser/main/lib/AwsMobileAnalyticsConfig.js
  browser/main/lib/dataApi/attachmentManagement.js
  browser/main/lib/dataApi/renameStorage.js
  browser/main/lib/dataApi/resolveStorageData.js
  browser/main/lib/dataApi/resolveStorageNotes.js
  browser/main/lib/dataApi/toggleStorage.js
  browser/main/lib/eventEmitter.js
  browser/main/lib/ipcClient.js
  browser/main/store.js
  lib/main-app.js
Labels: next release (v0.11.12)

#2314 tag enhancements
  browser/components/NoteItem.js
  browser/components/TagListItem.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/TagSelect.js
  browser/main/NoteList/index.js
  browser/main/SideNav/index.js
  browser/main/modals/PreferencesModal/UiTab.js
  locales/en.json
  locales/fr.json
Labels: next release (v0.11.12)

#2499 store editor view into config
  browser/components/MarkdownEditor.js
  browser/main/Detail/ToggleModeButton.js
  browser/main/lib/ConfigManager.js
Labels: next release (v0.11.12)

#2394 add attributes to fence blocks
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/components/render/MermaidRender.js
  browser/lib/markdown-it-fence.js
  browser/lib/markdown-it-sanitize-html.js
  browser/lib/markdown.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
  yarn.lock
Labels: next release (v0.11.12)

#2395 add YAML for chart
  browser/components/MarkdownPreview.js
  browser/lib/markdown-it-fence.js
  browser/lib/markdown.js
  extra_scripts/codemirror/mode/bfm/bfm.js
  lib/main.html
  package.json
  yarn.lock
Labels: next release (v0.11.12)

#2451 Add French translations
  locales/en.json
  locales/fr.json
Labels: next release (v0.11.12)

#2448 Fix bug caused by poor regex
  browser/main/lib/ConfigManager.js
Labels: next release (v0.11.12)

#2346 add support to abbreviations, definition lists and subscript/superscript text
  browser/components/markdown.styl
  browser/lib/markdown-it-deflist.js
  browser/lib/markdown.js
  package.json
  tests/fixtures/markdowns.js
  tests/lib/markdown-test.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
  yarn.lock
Labels: in progress :construction:

#2579 fix paste
  browser/components/CodeEditor.js
Labels: next release (v0.11.12)

#2515 Add translation to Portuguese from Portugal
  browser/lib/Languages.js
  locales/pt-PT.json
Labels: help wanted :sos:, in review :sparkles:

#2595 fold headings
  lib/main.html
Labels: approved :+1:

#2589 fix 2530
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  tests/lib/get-todo-status-test.js
Labels: next release (v0.11.12)

#2571 Add vscode debug support
  .vscode/launch.json
  .vscode/tasks.json
  docs/debug.md
  package.json
  webpack.config.js
Labels: next release (v0.11.12)

#2590 enhancement for #2588
  browser/main/SideNav/index.js
Labels: next release (v0.11.12)

#2593 fix cursor position after expending snippet
  browser/components/CodeEditor.js
Labels: next release (v0.11.12)

#2492 Remove emacs keymap Ctrl-V binding to allow pasting
  browser/main/Main.js
Labels: next release (v0.11.12)

#2603 Update electron framework to version 3.0.8
  package.json
Labels: next release (v0.11.12)

#2504 Added PR Template and update docs
  PULL_REQUEST_TEMPLATE.md
  contributing.md
  docs/code_style.md
Labels: in review :sparkles:

#2620 fix2618
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
Labels: approved :+1:

#2611 Ability to go from 'editor with preview' mode to 'preview' using mouse
  browser/components/MarkdownPreview.js
Labels: approved :+1:

#2604 fix GUI style element for default theme
  browser/main/StatusBar/StatusBar.styl
Labels: next release (v0.11.12)

#2601 Zoom Controls
  browser/main/StatusBar/index.js
  lib/main-menu.js
Labels: next release (v0.11.12)

#2592 Fixed duplicate TOC Title jump error
  browser/lib/markdown-toc-generator.js
  browser/lib/markdown.js
  package.json
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
  yarn.lock
Labels: next release (v0.11.12)

#2399 Clear search when a new note is created
  browser/main/NoteList/index.js
Labels: next release (v0.11.12)
