Repository BoostIO/Boostnote, pull requests merged in 2018-10, with the labels that each got.

#2477 fix visual bug with preview
  browser/components/MarkdownEditor.styl
Labels: approved :+1:

#2476 alternate background color for table rows
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  extra_scripts/codemirror/mode/bfm/bfm.css
  extra_scripts/codemirror/mode/bfm/bfm.js
  gruntfile.js
  lib/main.html
  package.json
  yarn.lock
Labels: next release (v0.11.10)

#2449 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: next release (v0.11.10)

#2445 Add a Copy button the Snippets tab
  browser/main/modals/PreferencesModal/SnippetTab.js
Labels: approved :+1:

#2444 fix graphical bugs in snippet list
  browser/main/global.styl
  browser/main/modals/PreferencesModal/SnippetList.js
Labels: next release (v0.11.10)

#2460 Added linethrough checkbox & make it optional
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/lib/markdown.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
Labels: hacktoberfest

#2438 Fix TypeError thrown on the Snippets page
  browser/main/modals/PreferencesModal/SnippetTab.js
Labels: next release (v0.11.10)

#2414 Dracula theme
  browser/components/MarkdownPreview.js
  browser/components/NoteItem.styl
  browser/components/NoteItemSimple.styl
  browser/components/RealtimeNotification.styl
  browser/components/SideNavFilter.styl
  browser/components/SnippetTab.styl
  browser/components/StorageItem.styl
  browser/components/TodoListPercentage.styl
  browser/components/markdown.styl
  browser/components/render/MermaidRender.js
  browser/main/Detail/Detail.styl
  browser/main/Detail/FolderSelect.styl
  browser/main/Detail/InfoPanel.styl
  browser/main/Detail/MarkdownNoteDetail.styl
  browser/main/Detail/NoteDetailInfo.styl
  browser/main/Detail/SnippetNoteDetail.styl
  browser/main/Detail/TagSelect.styl
  browser/main/Detail/ToggleModeButton.styl
  browser/main/Main.js
  browser/main/NewNoteButton/NewNoteButton.styl
  browser/main/NoteList/NoteList.styl
  browser/main/SideNav/SideNav.styl
  browser/main/StatusBar/StatusBar.styl
  browser/main/TopBar/TopBar.styl
  browser/main/global.styl
  browser/main/lib/ConfigManager.js
  browser/main/modals/CreateFolderModal.styl
  browser/main/modals/NewNoteModal.styl
  browser/main/modals/PreferencesModal/ConfigTab.styl
  browser/main/modals/PreferencesModal/Crowdfunding.styl
  browser/main/modals/PreferencesModal/FolderItem.styl
  browser/main/modals/PreferencesModal/InfoTab.styl
  browser/main/modals/PreferencesModal/PreferencesModal.styl
  browser/main/modals/PreferencesModal/SnippetTab.styl
  browser/main/modals/PreferencesModal/StoragesTab.styl
  browser/main/modals/PreferencesModal/UiTab.js
  browser/styles/Detail/TagSelect.styl
  browser/styles/index.styl
Labels: next release (v0.11.10)

#2524 Moved custom CSS to bottom of style definitions so that it has higher precedence.
  browser/components/MarkdownPreview.js
Labels: approved :+1:

#2518 Change blog url
  browser/main/modals/PreferencesModal/InfoTab.js
  readme.md
Labels: in review :sparkles:

#2512 Prevent empty printed page with scroll-past-end
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.11)

#2506 fix color for even rows in table
  extra_scripts/codemirror/mode/bfm/bfm.css
  extra_scripts/codemirror/mode/bfm/bfm.js
  gruntfile.js
Labels: next release (v0.11.11)

#2503 Add button clear all checkboxes
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/components/TodoListPercentage.js
  browser/components/TodoListPercentage.styl
  browser/main/Detail/MarkdownNoteDetail.js
Labels: next release (v0.11.11)

#2510 Title will now be extracted from front matter if title: is present.
  browser/lib/findNoteTitle.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  tests/lib/find-title-test.js
Labels: next release (v0.11.11)

#2474 disable hyperlink for attachments
  extra_scripts/codemirror/addon/hyperlink/hyperlink.js
Labels: next release (v0.11.11)

#2497 delete tag through context menu
  browser/components/TagListItem.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Main.js
  browser/main/SideNav/index.js
  tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
Labels: next release (v0.11.11)

#2487 fix error generated by toggling split editor
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
Labels: next release (v0.11.11)
