Repository BoostIO/Boostnote, pull requests merged in 2018-05, with the labels that each got.

#1874 Issue 1827
  .eslintrc
  .travis.yml
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/main/lib/dataApi/attachmentManagement.js
  browser/main/lib/dataApi/exportNote.js
  tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
  tests/dataApi/attachmentManagement.test.js
Labels: in review

#1883 fix drag drop more than one note bug
  browser/main/NoteList/index.js
Labels: next release (v0.11.5)

#1865 Fix #1780: Use black text with white background for printing and export in all theme
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.5)

#1868 fix internal note link bug #1820
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.5)

#1870 Fix font color in code block(markdown preview)
  browser/components/markdown.styl
Labels: next release (v0.11.5)

#1873 Not showing unassigned tag in taglist
  browser/main/SideNav/index.js
  browser/main/store.js
Labels: next release (v0.11.5)

#1912 Codemirror multiplex support
  browser/components/CodeEditor.js
  browser/components/MarkdownPreview.js
  browser/lib/convertModeName.js
  browser/main/Detail/SnippetNoteDetail.js
  lib/main.html
Labels: next release (v0.11.5)

#1895 fix moving note across different storage bug
  browser/main/store.js
Labels: next release (v0.11.5)

#1899 Deleting of attachments -> fixes #1828 and fixes #740
  browser/components/CodeEditor.js
  browser/main/lib/dataApi/attachmentManagement.js
  tests/dataApi/attachmentManagement.test.js
Labels: in review

#1925 Fix #1003 Update CodeMirror version
  package.json
Labels: next release (v0.11.5)

#1887 Add configuration to render newlines as <br> or not
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/markdown.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
  tests/fixtures/markdowns.js
  tests/lib/markdown-test.js
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
Labels: in review

#1923 Move note with attachment to different storage Fix for #1788
  browser/main/SideNav/StorageItem.js
  browser/main/lib/dataApi/attachmentManagement.js
  browser/main/lib/dataApi/copyImage.js
  browser/main/lib/dataApi/moveNote.js
  package.json
  tests/dataApi/attachmentManagement.test.js
  yarn.lock
Labels: in review

#1929 Shortcut to toggle mode
  browser/lib/utils.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Main.js
  browser/main/lib/ConfigManager.js
  browser/main/lib/shortcut.js
  browser/main/lib/shortcutManager.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  package.json
  yarn.lock
Labels: next release (v0.11.6)

#1965 standardrize sidebar tooltips
  browser/components/SideNavFilter.styl
  browser/components/StorageItem.styl
  browser/main/SideNav/StorageItem.styl
Labels: next release (v0.11.6)

#1939 Cloning a note should clone attachments
  browser/main/NoteList/index.js
  browser/main/lib/dataApi/attachmentManagement.js
  tests/dataApi/attachmentManagement.test.js
Labels: next release (v0.11.6)

#1931 Refresh taglist to remove unused tags on deleting
  browser/main/Detail/TagSelect.js
Labels: next release (v0.11.6)

#1936 deleting a folder should also delete the attachments -> fixes #1903
  browser/main/lib/dataApi/deleteFolder.js
  tests/dataApi/deleteFolder-test.js
  tests/dataApi/exportFolder-test.js
Labels: next release (v0.11.6)

#1987 [Feature Request] - 1638 - Support for admonitions
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
  browser/lib/markdown.js
  package.json
  resources/fonts/MaterialIcons-Regular.ttf
  resources/fonts/MaterialIcons-Regular.woff
  resources/fonts/MaterialIcons-Regular.woff2
  webpack-skeleton.js
  yarn.lock
Labels: in progress

#1970 update locales/ko
  locales/ko.json
Labels: in review

#1932 Refactoring of store.js
  browser/main/store.js
Labels: in progress
