Repository BoostIO/Boostnote, pull requests merged in 2018-09, with the labels that each got.

#2313 add EditorConfig
  .editorconfig
Labels: next release (v0.11.10)

#2304 add Monokai style for SnippetTab
  browser/components/SnippetTab.styl
Labels: in review :sparkles:

#2344 Fix text not readable for Monokai theme while creating new folder
  browser/styles/index.styl
Labels: next release (v0.11.10)

#2352 add default language for snippet note
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/NewNoteButton/index.js
  browser/main/modals/NewNoteModal.js
  browser/main/modals/PreferencesModal/ConfigTab.styl
  browser/main/modals/PreferencesModal/UiTab.js
  locales/en.json
  locales/fr.json
Labels: next release (v0.11.10)

#2345 Fix scroll for long table
  browser/components/markdown.styl
Labels: next release (v0.11.10)

#2355 Statusbar height fix
  browser/styles/index.styl
Labels: next release (v0.11.10)

#2320 add tag autocomplete
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/NoteDetailInfo.styl
  browser/main/Detail/TagSelect.js
  browser/main/Detail/TagSelect.styl
  browser/main/global.styl
  browser/styles/Detail/TagSelect.styl
  lib/main.html
  package.json
  yarn.lock
Labels: next release (v0.11.10)

#2329 Update contributing.md
  contributing.md
Labels: next release (v0.11.10)

#2363 Add Polish translations
  locales/pl.json
Labels: in progress :construction:

#2347 add support to front-matter
  browser/lib/findNoteTitle.js
  browser/lib/markdown-it-frontmatter.js
  browser/lib/markdown.js
  tests/lib/find-title-test.js
Labels: next release (v0.11.10)

#2337 fixing bug #2321
  browser/main/SideNav/index.js
Labels: next release (v0.11.10)

#2281 Automatic table of contents generation for Markdown
  browser/lib/markdown-toc-generator.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  lib/main-menu.js
  package.json
  tests/helpers/setup-browser-env.js
  tests/lib/markdown-toc-generator-test.js
  webpack-skeleton.js
Labels: next release (v0.11.10)

#2369 Implementing option `ui.defaultNote`
  browser/lib/newNote.js
  browser/main/NewNoteButton/index.js
  browser/main/modals/NewNoteModal.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: next release (v0.11.10)

#2371 Tags over the editor are clickable
  browser/main/Detail/TagSelect.js
  browser/main/Detail/TagSelect.styl
  yarn.lock
Labels: next release (v0.11.10)

#2386 Make notification sticky to the Save button
  browser/main/modals/PreferencesModal/ConfigTab.styl
Labels: next release (v0.11.10)

#2402 fix a bug causing right click to copy a note -- fixes #1833
  browser/main/NoteList/index.js
Labels: next release (v0.11.10)

#2403 Clarify contributing.md
  contributing.md
Labels: next release (v0.11.10)

#2404 improve error message grammar
  browser/main/modals/PreferencesModal/Blog.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: next release (v0.11.10)

#2389 fix admonitions -> use the "legacy" types and pass them as options to…
  browser/lib/markdown.js
Labels: next release (v0.11.10)

#2410 change storage header from Storages to Storage Locations
  browser/main/Main.js
  browser/main/modals/PreferencesModal/StoragesTab.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es-ES.json
  locales/fa.json
  locales/fr.json
  locales/hu.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru.json
  locales/sq.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: next release (v0.11.10)

#2412 Add text-overflow: ellipsis to FolderItem
  browser/main/modals/PreferencesModal/FolderItem.styl
  browser/main/modals/PreferencesModal/StorageItem.styl
Labels: next release (v0.11.10)

#2418 Implementing a context menu handler to show an attachment in the expl…
  browser/components/MarkdownPreview.js
  package.json
  yarn.lock
Labels: next release (v0.11.10)

#2437 Change Toggle Editor Mode hotkey on OS X
  browser/main/lib/ConfigManager.js
Labels: next release (v0.11.10)

#2442 Change You Have to Save! copy to Unsaved Changes!
  browser/main/modals/PreferencesModal/Blog.js
  browser/main/modals/PreferencesModal/HotkeyTab.js
  browser/main/modals/PreferencesModal/UiTab.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es-ES.json
  locales/fa.json
  locales/fr.json
  locales/hu.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru.json
  locales/sq.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: in review :sparkles:

#2436 Display timestamp on all notes
  browser/components/NoteItem.js
Labels: next release (v0.11.10)

#2428 Monokai theme fixes
  browser/components/NoteItem.styl
  browser/components/NoteItemSimple.styl
  browser/components/TodoListPercentage.styl
  browser/main/Detail/TagSelect.styl
  browser/main/Detail/ToggleModeButton.styl
  browser/styles/index.styl
Labels: next release (v0.11.10)

#2322 Fix drop image rotate wrong
  browser/main/lib/dataApi/attachmentManagement.js
Labels: next release (v0.11.10)
