Repository BoostIO/Boostnote, pull requests merged in 2019-06, with the labels that each got.

#3050 Fix #2540
  browser/lib/markdown.js
Labels: approved :+1:

#2998 Fix #2922
  package.json
  tests/lib/snapshots/markdown-test.js.md
  tests/lib/snapshots/markdown-test.js.snap
  yarn.lock
Labels: in review :sparkles:

#2994 Fixes that TOC hasn't id attribute when the title is all 2-byte characters
  browser/components/MarkdownPreview.js
  browser/lib/markdown-toc-generator.js
  browser/lib/slugify.js
  tests/lib/slugify-test.js
Labels: Need more review :mag_right:, approved :+1:

#3037 Simplified search input & fixed chinese character input
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/TopBar/index.js
  package.json
  yarn.lock
Labels: approved :+1:
