Repository BoostIO/Boostnote, pull requests merged in 2019-05, with the labels that each got.

#2846 Introduce markdownlint #864
  browser/components/CodeEditor.js
  lib/main.html
  package.json
Labels: approved :+1:, in progress :construction:

#2910 Sorting notes alphabetically now sort starting numbers in titles right
  browser/main/NoteList/index.js
Labels: in review :sparkles:

#3000 Add React hooks section to code style guide
  docs/code_style.md
Labels: Need more review :mag_right:, approved :+1:

#2966 Fixed typo on string 137
  locales/es-ES.json
Labels: approved :+1:

#3032 Fixed formatting
  browser/lib/Languages.js
Labels: approved :+1:

#3013 Make buttons undraggable
  browser/main/Detail/MarkdownNoteDetail.styl
Labels: approved :+1:

#3001 Fix regular expression related checkbox logic
  browser/components/MarkdownEditor.js
  browser/components/MarkdownSplitEditor.js
  browser/lib/getTodoStatus.js
  tests/lib/get-todo-status-test.js
Labels: in progress :construction:
