Repository BoostIO/Boostnote, pull requests merged in 2019-04, with the labels that each got.

#2962 Add "Ctrl + /" and "Shift + Ctrl + /" to insert today's date and time
  browser/components/CodeEditor.js
Labels: Need more review :mag_right:, approved :+1:

#2945 Removed erroneous parameter resulting in PlantUML server URL not being used
  browser/lib/markdown.js
Labels: in review :sparkles:

#2888 add default value to custom CSS editor
  browser/main/modals/PreferencesModal/UiTab.js
Labels: approved :+1:

#2883 Fixed bug-2875
  browser/components/MarkdownPreview.js
Labels: Need more review :mag_right:, approved :+1:
