Repository BoostIO/Boostnote, pull requests merged in 2019-01, with the labels that each got.

#2768 new feature: auto detect snippet language
  browser/components/CodeEditor.js
  browser/lib/newNote.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/modals/PreferencesModal/UiTab.js
  package.json
Labels: next release (v0.11.13)

#2764 Add Japanese translation
  locales/ja.json
Labels: next release (v0.11.13)

#2771 typo on pt-BR.json
  locales/pt-BR.json
Labels: next release (v0.11.13)

#2762 Update mousetrap
  package.json
Labels: next release (v0.11.13)

#2770 Replace current fullscreen button of SnippetNote to FullscreenButton module
  browser/main/Detail/SnippetNoteDetail.js
Labels: next release (v0.11.13)

#2758 add feature: colored tags
  browser/components/ColorPicker.js
  browser/components/ColorPicker.styl
  browser/components/NoteItem.js
  browser/components/TagListItem.js
  browser/components/TagListItem.styl
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/Detail/TagSelect.js
  browser/main/NoteList/index.js
  browser/main/SideNav/index.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/FolderItem.styl
  package.json
  resources/icon/icon-x-light.svg
  tests/components/TagListItem.snapshot.test.js
  tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
Labels: next release (v0.11.13)

#2720 show the scroll bar when the tag list is overflow
  browser/main/Detail/TagSelect.styl
  browser/styles/Detail/TagSelect.styl
Labels: next release (v0.11.13)

#2712 fix issues #2644 and #2662
  browser/components/MarkdownPreview.js
Labels: next release (v0.11.13)

#2795 Updated build.md to include directions for checking out PRs
  docs/build.md
Labels: next release (v0.11.13)

#2797 Update copywrite year
  LICENSE
  browser/main/modals/PreferencesModal/InfoTab.js
  readme.md
Labels: next release (v0.11.13)

#2811 Added cheatsheets to menu
  lib/main-menu.js
Labels: next release (v0.11.13)

#2801 Removal of USB drive will no longer cause irreparable damage.
  browser/main/lib/dataApi/init.js
Labels: approved :+1:

#2598 Fix the auto-updating numbered list to the middle of a list
  extra_scripts/boost/boostNewLineIndentContinueMarkdownList.js
Labels: next release (v0.11.13)

#2791 Update app background
  browser/main/global.styl
Labels: next release (v0.11.13)

#2774 #2194 - fixes Hotkey not working
  browser/main/lib/ConfigManager.js
Labels: in review :sparkles:

#2798 Disable updates in dev
  lib/main-app.js
Labels: in progress :construction:

#2661 Fixed lock button behavior and display
  browser/components/MarkdownEditor.js
  browser/main/Detail/MarkdownNoteDetail.js
Labels: Need more review :mag_right:, approved :+1:

#2651 Fixed delete note not navigating to the next note
  browser/main/NoteList/index.js
Labels: next release (v0.11.13)

#2831 Change default editor font #1995
  browser/main/lib/ConfigManager.js
Labels: approved :+1:

#2809 Zoom in and out image #1448
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
Labels: approved :+1:
