Repository BoostIO/Boostnote, pull requests merged in 2019-03, with the labels that each got.

#2868 [Fix] Cloning a note will now clone more note properties
  browser/main/NoteList/index.js
Labels: Need more review :mag_right:, approved :+1:

#2493 Add missing Chinese translation in preference page
  locales/zh-CN.json
  locales/zh-TW.json
Labels: approved :+1:

#2545 Add ~ and _ to autoclosing brackets
  browser/main/lib/ConfigManager.js
Labels: approved :+1:

#2678 Export a Markdown note as PDF
  browser/components/MarkdownPreview.js
  browser/main/Detail/InfoPanel.js
  browser/main/Detail/InfoPanel.styl
  browser/main/Detail/InfoPanelTrashed.js
  browser/main/Detail/MarkdownNoteDetail.js
  browser/main/Detail/SnippetNoteDetail.js
  browser/main/NoteList/index.js
  browser/main/lib/dataApi/exportFolder.js
  browser/main/lib/dataApi/exportNote.js
  lib/main-menu.js
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es-ES.json
  locales/fa.json
  locales/fr.json
  locales/hu.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/no.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ru.json
  locales/sq.json
  locales/th.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: approved :+1:

#2819 [Feature] Edit from preview
  browser/components/CodeEditor.js
  browser/components/MarkdownEditor.js
  browser/components/MarkdownPreview.js
Labels: Need more review :mag_right:, approved :+1:

#2864 Refactor code editor by moving the expand snippet out to a separate file
  browser/components/CodeEditor.js
  browser/lib/CMLanguageList.js
  browser/lib/SnippetManager.js
  browser/main/modals/PreferencesModal/SnippetEditor.js
Labels: Need more review :mag_right:, approved :+1:

#2914 Fix copy button
  browser/components/MarkdownPreview.js
Labels: approved :+1:

#2929 Upgrade Travis CI node and npm versions
  .travis.yml
Labels: in review :sparkles:
