Repository BoostIO/Boostnote, pull requests merged in 2020-01, with the labels that each got.

#3400 Updated Japanese document about contribution
  contributing.md
Labels: awaiting review :sparkle:

#3425 Refine Chinese translation
  locales/zh-CN.json
Labels: approved :+1:, help wanted :sos:

#3437 Added Wiki Link to Help Menu
  lib/main-menu.js
Labels: approved :+1:
