Repository BoostIO/Boostnote, pull requests merged in 2020-02, with the labels that each got.

#2879 add Nord UI theme
  browser/components/MarkdownPreview.js
  browser/components/MarkdownSplitEditor.styl
  browser/components/NavToggleButton.styl
  browser/components/NoteItem.styl
  browser/components/NoteItemSimple.styl
  browser/components/RealtimeNotification.styl
  browser/components/SideNavFilter.styl
  browser/components/SnippetTab.styl
  browser/components/StorageItem.styl
  browser/components/TagListItem.styl
  browser/components/TodoListPercentage.styl
  browser/components/markdown.styl
  browser/components/render/MermaidRender.js
  browser/lib/ui-themes.js
  browser/main/Detail/Detail.styl
  browser/main/Detail/FolderSelect.styl
  browser/main/Detail/FullscreenButton.styl
  browser/main/Detail/InfoPanel.styl
  browser/main/Detail/MarkdownNoteDetail.styl
  browser/main/Detail/NoteDetailInfo.styl
  browser/main/Detail/SnippetNoteDetail.styl
  browser/main/Detail/TagSelect.styl
  browser/main/Detail/ToggleDirectionButton.styl
  browser/main/Detail/ToggleModeButton.styl
  browser/main/Main.js
  browser/main/NewNoteButton/NewNoteButton.styl
  browser/main/NoteList/NoteList.styl
  browser/main/SideNav/PreferenceButton.styl
  browser/main/SideNav/SideNav.styl
  browser/main/SideNav/StorageItem.styl
  browser/main/SideNav/SwitchButton.styl
  browser/main/StatusBar/StatusBar.styl
  browser/main/TopBar/TopBar.styl
  browser/main/global.styl
  browser/main/lib/ConfigManager.js
  browser/main/modals/CreateFolderModal.styl
  browser/main/modals/CreateMarkdownFromURLModal.styl
  browser/main/modals/NewNoteModal.styl
  browser/main/modals/PreferencesModal/ConfigTab.styl
  browser/main/modals/PreferencesModal/Crowdfunding.styl
  browser/main/modals/PreferencesModal/FolderItem.styl
  browser/main/modals/PreferencesModal/InfoTab.styl
  browser/main/modals/PreferencesModal/PreferencesModal.styl
  browser/main/modals/PreferencesModal/SnippetTab.styl
  browser/main/modals/PreferencesModal/StorageItem.styl
  browser/main/modals/PreferencesModal/StoragesTab.styl
  browser/main/modals/PreferencesModal/UiTab.js
  browser/main/modals/RenameFolderModal.styl
  browser/styles/Detail/TagSelect.styl
  browser/styles/index.styl
Labels: approved :+1:

#3453 update Korean section of contributing.md
  contributing.md
Labels: awaiting review :sparkle:

#3451 extended language support for multiple languages
  locales/fa.json
  locales/hu.json
  locales/ja.json
  locales/ko.json
  locales/pl.json
  locales/ru.json
  locales/th.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: approved :+1:

#3304 Include build dependency packages cmds on build docs
  docs/build.md
Labels: awaiting review :sparkle:

#3476 Fixed wrong handler for setting button
  browser/main/SideNav/index.js
Labels: approved :+1:

#3472 Dropdown colour (theme aware)
  browser/main/NoteList/NoteList.styl
Labels: approved :+1:

#3215 [WIP]h1 padding bottom value changed
  browser/components/MarkdownPreview.js
  browser/components/markdown.styl
Labels: approved :+1:

#2713 Scroll Bars can now be hidden
  browser/components/MarkdownPreview.js
  browser/main/index.js
  browser/main/lib/ConfigManager.js
  browser/main/modals/PreferencesModal/UiTab.js
Labels: approved :+1:

#3490 Unable to scroll when there are many folders
  browser/components/StorageList.styl
Labels: approved :+1:

#3002 Add tag link handling with :tag:#tag syntax
  browser/components/MarkdownPreview.js
  extra_scripts/codemirror/addon/hyperlink/hyperlink.js
Labels: approved :+1:

#3489 Update issue template
  ISSUE_TEMPLATE.md
Labels: needs extra review :mag_right:

#3498 updated PR template
  PULL_REQUEST_TEMPLATE.md
Labels: approved :+1:
